wearefrank/haalcentraal-connector

pom.xml

Apply fix from skeleton repo that adds dummy pom.xml so the frank-runner recognizes maven project structure.

patch: apply fix from skeleton repository

---

docker-compose-postgres.yaml
init.sql

Added an init script to the project to define the structure of the postgres database on startup in docker

fix: Add init script for postgres database

---

docker-compose-postgres.yaml
init.sql
src/main/configurations/subscription-management-and-processing/DatabaseChangelog.xml
src/main/configurations/subscription-management-and-processing/StageSpecifics_LOC.properties

Replace the sql init file with a database changelog file that adds the personen table

Gt 1085 afnemersindicator sql error

---

docker-compose-postgres.yaml
servers.json

Create a servers.json file to specify databases for pgadmin to automatically connect to.

Automatically connect pgadmin to database server

---

README.md

Write description for subscription management

Add file structure to README

---

src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenAfnemersIndicatieProcessor.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenUpdate.xml

Subscription management cleanup

---

src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenSynchronizePersoon.xml
src/main/resources/JSONcompare.js

Rework the jsoncompare function to only have one return type, and rename variable names for readability

Javascript refactor

---

src/main/configurations/subscription-management-and-processing/Configuration.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenAfnemersIndicatieReceiver.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenCallbackSender.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenUpdateAndNotify.xml
src/main/configurations/subscription-management-and-processing/Configuration_QueueNotificationTask.xml
src/main/configurations/subscription-management-and-processing/jsonnet/ApplicationsFilter.jsonnet
src/main/configurations/subscription-management-and-processing/jsonnet/ExtractDatabaseRows.jsonnet
src/main/configurations/subscription-management-and-processing/jsonnet/FilterApplicationsById.jsonnet

Added a notification task store to notify new and existing subscribers of the current state of the data

Notification system

---

README.md
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenNotificationProcessor.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenNotificationReceiver.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenSynchronizePersoon.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenUpdateAndNotify.xml
src/main/configurations/subscription-management-and-processing/DatabaseChangelog.xml

Retry synchronization tasks when synchronization yielded no new data.

FEAT: Synchronization retry mechanism

---

src/main/configurations/brp-personen-bevragen-outway/Configuration-brp-pb-outway.xml
src/main/configurations/oauth/Configuration_UpdateToken.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenSynchronizePersoon.xml

Check if the response of the brp-outway was an empty personen array before processing

Check empty response

---

src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenAfnemersIndicatieReceiver.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenCallbackSender.xml
src/main/configurations/subscription-management-and-processing/Configuration_QueueNotificationTask.xml
src/main/configurations/subscription-management-and-processing/json/ApplicationConfig.json
src/main/configurations/subscription-management-and-processing/jsonnet/ApplicationsFilter.jsonnet
src/main/configurations/subscription-management-and-processing/jsonnet/FilterApplicationsById.jsonnet

Updates the flow of the subscription management system to use the name of the application instead of an arbitrary id.

Refactor app

---

src/main/resources/ladybug/DatabaseChangelog_Custom.xml

This reverts commit 88927b068bc50e3eb92fa028127cc5e11f179ec6.

Revert "feat: add ladybug column to database"

---

src/main/resources/springIbisTestToolCustom.xml

This reverts commit 030fbcfa0329dc8d4d46801009b20e15114803c0.

Revert "feat: add ladybug column BSN"

---

Dockerfile
src/main/java/nl/nn/testtool/metadata/RegexMetadataFieldExtractor.java
src/main/java/nl/nn/testtool/metadata/RegexMetadataFieldExtractor.old

Add custom code for ladybug to prevent a NullPointerException when a checkpoint message is null.

Fix ladybug npe

---

docker-compose.frank.stub.yaml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenAfnemersIndicatieReceiver.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenCallbackSender.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenUpdateAndNotify.xml
src/main/configurations/subscription-management-and-processing/Configuration_EndpointRouter.xml
src/main/configurations/subscription-management-and-processing/Configuration_QueueNotificationTask.xml
src/main/configurations/subscription-management-and-processing/json/ApplicationConfig.json
src/main/configurations/subscription-management-and-processing/xsl/mappingJsonToStuf.xslt
src/test/testtool/subscription-management-and-processing/afnemersindicaties/01/in.xml
src/test/testtool/subscription-management-and-processing/afnemersindicaties/01/out.xml
src/test/testtool/subscription-management-and-processing/afnemersindicaties/01/task.json
src/test/testtool/subscription-management-and-processing/afnemersindicaties/02/task.json

Adds mutatiesoort to callback message.

fix: add mutatiesoort to callback task and callback message

---

src/main/configurations/subscription-management-and-processing/Configuration_CreateBulkImportTasks.xml
src/main/configurations/subscription-management-and-processing/Configuration_ProcessBulkImportTask.xml
src/main/configurations/subscription-management-and-processing/DatabaseChangelog.xml
src/main/configurations/subscription-management-and-processing/xsl/computeSubscriptionStates.xsl

Bulk import keys

---

src/main/configurations/brp-personen-bevragen-outway/Configuration-brp-call-diginetwerk.xml
src/main/configurations/brp-personen-bevragen-outway/Configuration-brp-call-proefomgeving.xml
src/main/configurations/brp-personen-bevragen-outway/Configuration-brp-pb-outway.xml
src/main/configurations/brp-personen-bevragen-outway/DeploymentSpecifics.properties
src/main/configurations/oauth/Configuration_UpdateToken.xml

Adds a property to define the environment setting to specify the endpoints that need to be used.
Updates the brp flow to use the oauth feature from the HttpSender, and disables the token scheduler.

Add configurable environment variable.

---

src/main/configurations/brp-personen-bevragen-outway/DeploymentSpecifics.properties

add a second oauth token endpoint for the staging environment

add separate token endpoint for staging environment

---

src/main/configurations/brp-personen-bevragen-outway/Configuration-brp-call-diginetwerk.xml

This reverts commit 4e8cbe89b02381359c72512c85c473e083bf89e9.

Revert "change auth method to query params"

---

src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenCallbackSender.xml
src/main/configurations/subscription-management-and-processing/Configuration_ProcessBulkImportBAG.xml
src/main/configurations/subscription-management-and-processing/xsl/computeKeyStates.xsl

fix more things for bagkeys for brp

Bag for brp

---

src/main/configurations/brp-personen-bevragen-outway/DeploymentSpecifics.properties
src/main/resources/DeploymentSpecifics.properties

fixes the oauth flow, by moving the properties within scope of all sub-configurations

fix: move properties to resource folder

---

src/main/configurations/brp-personen-bevragen-outway/Configuration-brp-pb-outway.xml
src/main/configurations/oauth/Configuration_UpdateToken.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpGetPersoon.xml
src/main/configurations/subscription-management-and-processing/Configuration_BrpPersonenSynchronizePersoon.xml
src/main/resources/DeploymentSpecifics.properties

- fix looping issue
- rename properties
- add overwrite on create token.txt

File overwrite

---

src/main/configurations/brp-personen-bevragen-soap/xsl/mappingJsonToStuf.xslt
src/main/configurations/subscription-management-and-processing/xsl/mappingJsonToStuf.xslt

Fixes date formatting for datumVerkrijgingVerblijfstitel

Date formatting
